@ApiAddress = https://localhost:7246
@loginEmail = admin@admin.com
@loginPassword = Admin123$

### Create new user
POST {{ApiAddress}}/register
Accept: application/json
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "Admin123$"
}

### Login existing user
POST {{ApiAddress}}/login
Accept: application/json
Content-Type: application/json

{
  "email": "{{loginEmail}}",
  "password": "{{loginPassword}}"
}

> {%
    client.global.set("AccessToken", response.body.accessToken); 
 %}

### GET Task Categories
GET {{ApiAddress}}/taskcategory/
Accept: application/json
Authorization: Bearer {{AccessToken}}

### GET Task Category by ID
GET {{ApiAddress}}/taskcategory/3
Accept: application/json
Authorization: Bearer {{AccessToken}}

### GET Task by ID
GET {{ApiAddress}}/task/1
Accept: application/json
Authorization: Bearer {{AccessToken}}

### Create new Task Category
POST {{ApiAddress}}/taskcategory/
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
  "categoryName": "Task category assigned to a user",
  "startTime": "02:00:00",
  "endTime": "11:00:00"
}
