services:
  core:
    image: core-api
    build:
      context: .
      dockerfile: Core/Dockerfile
  
  database:
      image: docker.io/postgres:17
      ports:
        - "3032:5432"
      environment:
        POSTGRES_USER: "patryk"
        POSTGRES_PASSWORD: "pQ7mPP##Wrsfon@~"
        POSTGRES_DB: "dashboard"
      volumes:
        - ./Data:/var/lib/postgresql/data