services:
  core:
    image: core-api
    build:
      context: .
      dockerfile: Core/Dockerfile
    ports:
      - "3080:8080"
    environment:
      ConnectionStrings__DashboardDatabase: "Server=database;Port=5432;Database=dashboard;User Id=patryk;Password=pQ7mPP##Wrsfon@~;CommandTimeout=10;Timeout=10"
  database:
      image: docker.io/postgres:17
      ports:
        - "3032:5432"
      environment:
        POSTGRES_USER: "patryk"
        POSTGRES_PASSWORD: "pQ7mPP##Wrsfon@~"
        POSTGRES_DB: "dashboard"
      volumes:
        - ./Data:/var/lib/postgresql/data